# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 1014)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.collectionsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionsTab.sizePolicy().hasHeightForWidth())
        self.collectionsTab.setSizePolicy(sizePolicy)
        self.collectionsTab.setObjectName("collectionsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.collectionsTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.collectionsTree = QtWidgets.QTreeView(self.collectionsTab)
        self.collectionsTree.setObjectName("collectionsTree")
        self.verticalLayout_2.addWidget(self.collectionsTree)
        self.tabWidget.addTab(self.collectionsTab, "")
        self.historyTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyTab.sizePolicy().hasHeightForWidth())
        self.historyTab.setSizePolicy(sizePolicy)
        self.historyTab.setObjectName("historyTab")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.historyTab)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.historyList = QtWidgets.QListWidget(self.historyTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyList.sizePolicy().hasHeightForWidth())
        self.historyList.setSizePolicy(sizePolicy)
        self.historyList.setObjectName("historyList")
        self.verticalLayout_31.addWidget(self.historyList)
        self.tabWidget.addTab(self.historyTab, "")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.method = QtWidgets.QComboBox(self.layoutWidget)
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.horizontalLayout.addWidget(self.method)
        self.url = QtWidgets.QLineEdit(self.layoutWidget)
        self.url.setObjectName("url")
        self.horizontalLayout.addWidget(self.url)
        self.sendButton = QtWidgets.QPushButton(self.layoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget1 = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget1.setObjectName("tabWidget1")
        self.inputHeadersTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputHeadersTab.sizePolicy().hasHeightForWidth())
        self.inputHeadersTab.setSizePolicy(sizePolicy)
        self.inputHeadersTab.setObjectName("inputHeadersTab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.inputHeadersTab)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.inputHeaders = QtWidgets.QTableWidget(self.inputHeadersTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputHeaders.sizePolicy().hasHeightForWidth())
        self.inputHeaders.setSizePolicy(sizePolicy)
        self.inputHeaders.setRowCount(0)
        self.inputHeaders.setColumnCount(2)
        self.inputHeaders.setObjectName("inputHeaders")
        item = QtWidgets.QTableWidgetItem()
        self.inputHeaders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputHeaders.setHorizontalHeaderItem(1, item)
        self.inputHeaders.horizontalHeader().setVisible(False)
        self.inputHeaders.horizontalHeader().setCascadingSectionResizes(True)
        self.inputHeaders.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_21.addWidget(self.inputHeaders)
        self.tabWidget1.addTab(self.inputHeadersTab, "")
        self.reqBodyTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqBodyTab.sizePolicy().hasHeightForWidth())
        self.reqBodyTab.setSizePolicy(sizePolicy)
        self.reqBodyTab.setObjectName("reqBodyTab")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.reqBodyTab)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formDataButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.formDataButton.setObjectName("formDataButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.formDataButton)
        self.horizontalLayout_2.addWidget(self.formDataButton)
        self.formUrlEncodedButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.formUrlEncodedButton.setObjectName("formUrlEncodedButton")
        self.buttonGroup.addButton(self.formUrlEncodedButton)
        self.horizontalLayout_2.addWidget(self.formUrlEncodedButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.reqBodyTab)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.binaryButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.binaryButton.setObjectName("binaryButton")
        self.buttonGroup.addButton(self.binaryButton)
        self.horizontalLayout_2.addWidget(self.binaryButton)
        self.comboBox = QtWidgets.QComboBox(self.reqBodyTab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.requestBody = QtWidgets.QTextEdit(self.reqBodyTab)
        self.requestBody.setObjectName("requestBody")
        self.verticalLayout_22.addWidget(self.requestBody)
        self.tabWidget1.addTab(self.reqBodyTab, "")
        self.verticalLayout.addWidget(self.tabWidget1)
        self.reqStatusLayout = QtWidgets.QHBoxLayout()
        self.reqStatusLayout.setContentsMargins(6, -1, -1, -1)
        self.reqStatusLayout.setObjectName("reqStatusLayout")
        self.statusCode = QtWidgets.QLabel(self.layoutWidget)
        self.statusCode.setText("")
        self.statusCode.setObjectName("statusCode")
        self.reqStatusLayout.addWidget(self.statusCode)
        self.time = QtWidgets.QLabel(self.layoutWidget)
        self.time.setText("")
        self.time.setObjectName("time")
        self.reqStatusLayout.addWidget(self.time)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.reqStatusLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.reqStatusLayout)
        self.tabWidget2 = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget2.setObjectName("tabWidget2")
        self.responseTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.responseTab.sizePolicy().hasHeightForWidth())
        self.responseTab.setSizePolicy(sizePolicy)
        self.responseTab.setObjectName("responseTab")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.responseTab)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.responseText = QtWidgets.QTextBrowser(self.responseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.responseText.sizePolicy().hasHeightForWidth())
        self.responseText.setSizePolicy(sizePolicy)
        self.responseText.setObjectName("responseText")
        self.verticalLayout_23.addWidget(self.responseText)
        self.tabWidget2.addTab(self.responseTab, "")
        self.headersTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headersTab.sizePolicy().hasHeightForWidth())
        self.headersTab.setSizePolicy(sizePolicy)
        self.headersTab.setObjectName("headersTab")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.headersTab)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.headersText = QtWidgets.QTextBrowser(self.headersTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headersText.sizePolicy().hasHeightForWidth())
        self.headersText.setSizePolicy(sizePolicy)
        self.headersText.setObjectName("headersText")
        self.verticalLayout_32.addWidget(self.headersText)
        self.tabWidget2.addTab(self.headersTab, "")
        self.verticalLayout.addWidget(self.tabWidget2)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget1.setCurrentIndex(1)
        self.tabWidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.collectionsTab), _translate("MainWindow", "Collections"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historyTab), _translate("MainWindow", "History"))
        self.method.setItemText(0, _translate("MainWindow", "GET"))
        self.method.setItemText(1, _translate("MainWindow", "POST"))
        self.method.setItemText(2, _translate("MainWindow", "PUT"))
        self.method.setItemText(3, _translate("MainWindow", "PATCH"))
        self.method.setItemText(4, _translate("MainWindow", "DELETE"))
        self.method.setItemText(5, _translate("MainWindow", "COPY"))
        self.method.setItemText(6, _translate("MainWindow", "HEAD"))
        self.method.setItemText(7, _translate("MainWindow", "OPTIONS"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        item = self.inputHeaders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Key"))
        item = self.inputHeaders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.inputHeadersTab), _translate("MainWindow", "Headers"))
        self.formDataButton.setText(_translate("MainWindow", "form-data"))
        self.formUrlEncodedButton.setText(_translate("MainWindow", "&x-www-form-urlencoded"))
        self.radioButton_2.setText(_translate("MainWindow", "raw"))
        self.binaryButton.setText(_translate("MainWindow", "bi&nary"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Text"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Text (text/plain)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "JSON (application/json)"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Javascript (application/javascript)"))
        self.comboBox.setItemText(4, _translate("MainWindow", "XML (application/xml)"))
        self.comboBox.setItemText(5, _translate("MainWindow", "XML (text/xml)"))
        self.comboBox.setItemText(6, _translate("MainWindow", "HTML (text/html)"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.reqBodyTab), _translate("MainWindow", "Request body"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.responseTab), _translate("MainWindow", "Response"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.headersTab), _translate("MainWindow", "Headers"))

