# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Sun Feb 17 10:16:01 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1384, 609)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSplitter.sizePolicy().hasHeightForWidth())
        self.mainSplitter.setSizePolicy(sizePolicy)
        self.mainSplitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainSplitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setHandleWidth(2)
        self.mainSplitter.setObjectName("mainSplitter")
        self.collectionsHistoryLayoutWidget = QtWidgets.QWidget(self.mainSplitter)
        self.collectionsHistoryLayoutWidget.setObjectName("collectionsHistoryLayoutWidget")
        self.collectionsHistoryLayout = QtWidgets.QVBoxLayout(self.collectionsHistoryLayoutWidget)
        self.collectionsHistoryLayout.setContentsMargins(0, 0, 0, 0)
        self.collectionsHistoryLayout.setObjectName("collectionsHistoryLayout")
        self.layoutWidget = QtWidgets.QWidget(self.mainSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.centralLayout.setObjectName("centralLayout")
        self.reqUrlLayout = QtWidgets.QHBoxLayout()
        self.reqUrlLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.reqUrlLayout.setObjectName("reqUrlLayout")
        self.method = QtWidgets.QComboBox(self.layoutWidget)
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.method.addItem("")
        self.reqUrlLayout.addWidget(self.method)
        self.url = QtWidgets.QLineEdit(self.layoutWidget)
        self.url.setClearButtonEnabled(True)
        self.url.setObjectName("url")
        self.reqUrlLayout.addWidget(self.url)
        self.sendButton = QtWidgets.QPushButton(self.layoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.reqUrlLayout.addWidget(self.sendButton)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.reqUrlLayout.addWidget(self.saveButton)
        self.centralLayout.addLayout(self.reqUrlLayout)
        self.requestContentTabs = QtWidgets.QTabWidget(self.layoutWidget)
        self.requestContentTabs.setObjectName("requestContentTabs")
        self.inputHeadersTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputHeadersTab.sizePolicy().hasHeightForWidth())
        self.inputHeadersTab.setSizePolicy(sizePolicy)
        self.inputHeadersTab.setObjectName("inputHeadersTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inputHeadersTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputHeaders = QtWidgets.QTableWidget(self.inputHeadersTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputHeaders.sizePolicy().hasHeightForWidth())
        self.inputHeaders.setSizePolicy(sizePolicy)
        self.inputHeaders.setRowCount(0)
        self.inputHeaders.setColumnCount(2)
        self.inputHeaders.setObjectName("inputHeaders")
        self.inputHeaders.setColumnCount(2)
        self.inputHeaders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.inputHeaders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inputHeaders.setHorizontalHeaderItem(1, item)
        self.inputHeaders.horizontalHeader().setVisible(False)
        self.inputHeaders.horizontalHeader().setCascadingSectionResizes(True)
        self.inputHeaders.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.inputHeaders)
        self.requestContentTabs.addTab(self.inputHeadersTab, "")
        self.reqBodyTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqBodyTab.sizePolicy().hasHeightForWidth())
        self.reqBodyTab.setSizePolicy(sizePolicy)
        self.reqBodyTab.setObjectName("reqBodyTab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.reqBodyTab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.reqBodySwitcherLayout = QtWidgets.QHBoxLayout()
        self.reqBodySwitcherLayout.setContentsMargins(-1, 0, -1, -1)
        self.reqBodySwitcherLayout.setObjectName("reqBodySwitcherLayout")
        self.formDataButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.formDataButton.setObjectName("formDataButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.formDataButton)
        self.reqBodySwitcherLayout.addWidget(self.formDataButton)
        self.formUrlEncodedButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.formUrlEncodedButton.setObjectName("formUrlEncodedButton")
        self.buttonGroup.addButton(self.formUrlEncodedButton)
        self.reqBodySwitcherLayout.addWidget(self.formUrlEncodedButton)
        self.rawButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.rawButton.setObjectName("rawButton")
        self.buttonGroup.addButton(self.rawButton)
        self.reqBodySwitcherLayout.addWidget(self.rawButton)
        self.binaryButton = QtWidgets.QRadioButton(self.reqBodyTab)
        self.binaryButton.setObjectName("binaryButton")
        self.buttonGroup.addButton(self.binaryButton)
        self.reqBodySwitcherLayout.addWidget(self.binaryButton)
        self.comboBox = QtWidgets.QComboBox(self.reqBodyTab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.reqBodySwitcherLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.reqBodySwitcherLayout.addItem(spacerItem)
        self.verticalLayout_21.addLayout(self.reqBodySwitcherLayout)
        self.requestBody = QtWidgets.QTextEdit(self.reqBodyTab)
        self.requestBody.setObjectName("requestBody")
        self.verticalLayout_21.addWidget(self.requestBody)
        self.requestContentTabs.addTab(self.reqBodyTab, "")
        self.centralLayout.addWidget(self.requestContentTabs)
        self.layoutWidget2 = QtWidgets.QWidget(self.mainSplitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.responseLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.responseLayout.setContentsMargins(-1, 5, -1, 5)
        self.responseLayout.setObjectName("responseLayout")
        self.verticalLayout_3.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1384, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.requestContentTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "qTTp", None, -1))
        self.method.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "GET", None, -1))
        self.method.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "POST", None, -1))
        self.method.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "PUT", None, -1))
        self.method.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "PATCH", None, -1))
        self.method.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "DELETE", None, -1))
        self.method.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "COPY", None, -1))
        self.method.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "HEAD", None, -1))
        self.method.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "OPTIONS", None, -1))
        self.sendButton.setText(QtWidgets.QApplication.translate("MainWindow", "Send", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.inputHeaders.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Key", None, -1))
        self.inputHeaders.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Value", None, -1))
        self.requestContentTabs.setTabText(self.requestContentTabs.indexOf(self.inputHeadersTab), QtWidgets.QApplication.translate("MainWindow", "Headers", None, -1))
        self.formDataButton.setText(QtWidgets.QApplication.translate("MainWindow", "form-data", None, -1))
        self.formUrlEncodedButton.setText(QtWidgets.QApplication.translate("MainWindow", "&x-www-form-urlencoded", None, -1))
        self.rawButton.setText(QtWidgets.QApplication.translate("MainWindow", "raw", None, -1))
        self.binaryButton.setText(QtWidgets.QApplication.translate("MainWindow", "binar&y", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Text", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Text (text/plain)", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "JSON (application/json)", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Javascript (application/javascript)", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "XML (application/xml)", None, -1))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "XML (text/xml)", None, -1))
        self.comboBox.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "HTML (text/html)", None, -1))
        self.requestContentTabs.setTabText(self.requestContentTabs.indexOf(self.reqBodyTab), QtWidgets.QApplication.translate("MainWindow", "Request body", None, -1))

